#A second madlib story was added with new user inputs directly stored in variables alongside the printed prompt.

print('Ever enjoyed a game of crazy wacky story fill in the blank?')
print('There is a hungry story monster who wants some words.')
print('To start with it wants an adjective!')
adjective = input()
print('Now we must feed it an animal!')
animal = input()
print('Now give us a verb!')
verb_one = input()
print('We need to burp it, surprise it with an exclamation!')
exclamation = input().capitalize()
print('That was not enough, what verb can we use to help it?')
verb_two = input()
print('One more good verb and it will help.')
verb_three = input()
print('The story monster has some story it has to tell us now.')
print(f"The other day, I was really in trouble. It all started when I saw a very\n{adjective} {animal} {verb_one} down the hallway. '{exclamation}!' I yelled. But all\nI could think to do was to {verb_two} over and over. Miraculously,\nthat caused it to stop, but not before it tried to {verb_three}\nright in front of my family.")
print('How about another story?\nThis time the words will get spooky.')
adjective_one = input('Provide an adjective: ')
plural_food = input('Food plural: ')
verb_four = input('Now a verb: ')
saying = input('A common saying: ')
noun = input('A noun: ')
plural_food_two = input('Another food plural: ')
color = input('Pick a color: ')
vehicle = input('Something you would ride in: ')
animal_two = input('An animal: ')
person = input('Now a person: ')
print(f'Today I went to my favorite Taco Stand called the {adjective_one} {plural_food}.\nUnlike most food stands, they cook and prepare the food in a {vehicle} while you {verb_four}.\nThe best thing on the menu is the {color} {animal_two}.\nInstead of ground beef they fill the taco with {noun}, cheese, and top it off with a salsa made from {plural_food_two}.\nIf that does not make your mouth water, then it is just like {person} always says:{saying}!')